version: '3.9'
services:

  analysis:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    volumes:
    - "renv:/renv"

  mongo:
    image: mongo:4.2
    restart: always
    volumes: 
    - "dbdata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  dbdata:
  renv: